name: Linter
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Ruff
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.4.2
          args: 'check'

  pyright:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.10', '3.x']

    name: Pylint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
        with:
          version: '1.1.351'
          warnings: false
          no-comments: ${{ matrix.python-version != '3.x' }}
