name: Linter
on: [ push, pull_request ]
jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.4.2
          args: 'format --check'
